/**
 * Mentor G - PDF Report Generator
 * Copyright (c) 2026 Gregory Donarum
 * Licensed under MIT License with Commons Clause
 */

import type { AnalysisResponse, Finding } from '../types/analysis';

const SEVERITY_COLORS: Record<string, string> = {
  critical: '#dc3545',
  warning: '#fd7e14',
  info: '#0dcaf0',
  good: '#198754',
};

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function buildFindingHtml(finding: Finding): string {
  const color = SEVERITY_COLORS[finding.severity] ?? '#333';
  const codeBlock = finding.codeSnippet
    ? `<pre style="background:#f4f4f4;border:1px solid #ddd;border-radius:4px;padding:10px;font-size:12px;overflow-x:auto;white-space:pre-wrap;word-break:break-all;">${escapeHtml(finding.codeSnippet)}</pre>`
    : '';
  return `
    <div style="border:1px solid #ddd;border-left:5px solid ${color};border-radius:4px;padding:14px 16px;margin-bottom:16px;break-inside:avoid;">
      <div style="display:flex;align-items:center;gap:10px;margin-bottom:8px;">
        <span style="background:${color};color:#fff;font-size:11px;font-weight:700;padding:2px 8px;border-radius:12px;text-transform:uppercase;">${escapeHtml(finding.severity)}</span>
        <strong style="font-size:15px;">${escapeHtml(finding.title)}</strong>
      </div>
      <p style="margin-bottom:8px;color:#333;">${escapeHtml(finding.description)}</p>
      <div style="background:#f8f9fa;border-radius:4px;padding:10px;font-size:13px;">
        <strong>Fix:</strong> ${escapeHtml(finding.fix)}
      </div>
      ${codeBlock}
    </div>
  `;
}

export function generatePdfReport(analysis: AnalysisResponse, filenames: string[]): void {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const filesLine =
    filenames.length > 0
      ? `<p style="color:#555;font-size:13px;margin-top:4px;">Files analyzed: ${filenames.map(escapeHtml).join(', ')}</p>`
      : '';

  const findingsHtml = analysis.findings.map(buildFindingHtml).join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Mentor G – Robot Diagnostics Report</title>
  <style>
    @media print {
      body { margin: 0; }
      .no-print { display: none; }
    }
    body {
      font-family: Arial, Helvetica, sans-serif;
      color: #1a1a2e;
      line-height: 1.5;
      max-width: 800px;
      margin: 0 auto;
      padding: 24px;
      font-size: 14px;
    }
    h1 { font-size: 22px; margin-bottom: 4px; }
    h2 { font-size: 16px; margin: 20px 0 10px; border-bottom: 2px solid #e0e0e0; padding-bottom: 6px; }
  </style>
</head>
<body>
  <div style="border-bottom:3px solid #1a4fc4;padding-bottom:14px;margin-bottom:20px;">
    <h1 style="color:#1a4fc4;">&#129302; Mentor G – Robot Diagnostics Report</h1>
    <p style="color:#555;font-size:13px;">${escapeHtml(date)}</p>
    ${filesLine}
  </div>

  <h2>Summary</h2>
  <p style="margin-bottom:20px;">${escapeHtml(analysis.summary)}</p>

  <h2>Findings (${analysis.findings.length})</h2>
  ${findingsHtml.length > 0 ? findingsHtml : '<p style="color:#666;">No findings.</p>'}

  <p style="margin-top:32px;font-size:11px;color:#999;border-top:1px solid #eee;padding-top:10px;">
    Generated by Mentor G &mdash; AI-powered FRC robot diagnostics
  </p>

  <div class="no-print" style="margin-top:24px;text-align:center;">
    <button onclick="window.print()" style="padding:10px 24px;background:#1a4fc4;color:#fff;border:none;border-radius:6px;font-size:14px;cursor:pointer;">
      Save as PDF / Print
    </button>
  </div>
</body>
</html>`;

  const win = window.open('', '_blank');
  if (!win) {
    alert('Please allow popups to generate the PDF report.');
    return;
  }
  win.document.write(html);
  win.document.close();
}
